version: '3'

services:
  pg_db:
    image: postgres:14
    container_name: pg-node
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - /var/lib/postgres:/var/lib/postgresql/data
